### ISSUE TITLE
[BUG] Cura wont start after initial deploy

### ISSUE THREAD

**Issue by timota** [linuxserver/docker-cura#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When container deployed on unRaid and started, Cura crashed with traceback. 

### Expected Behavior

Cura should be started 

### Steps To Reproduce

unRaid. 
1. Goto Community apps
2. search and choose Cura
3. Install with default settings
4. Start container

### Environment

```markdown
- OS: unRaid 6.12.4
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run
  -d
  --name='cura'
  --net='bridge'
  -e TZ="Europe/London"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="ux-12"
  -e HOST_CONTAINERNAME="cura"
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:3000]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/cura-logo.png'
  -p '3000:3000/tcp'
  -p '3002:3001/tcp'
  -v '/mnt/cache/appdata/cura':'/config':'rw' 'lscr.io/linuxserver/cura'
e3d370345c9a28bb0dfde349aa9829c122220c8d11991d073bf5f127d57a798a
```
```


### Container logs

```bash
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

Xvnc KasmVNC 1.2.0 - built Nov 25 2023 18:51:09
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation

PyInstaller/loader/pyimod02_importers.py:352: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
QStandardPaths: wrong permissions on runtime directory /config/.XDG, 0755 instead of 0700

(UltiMaker-Cura:330): dbind-WARNING **: 13:03:57.654: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

[custom-init] No custom files found, skipping...
[ls.io-init] done.
Obt-Message: Xinerama extension is not present on the server
```

**Comment by timota** [comment]
Cura Error traceback
```
Traceback (most recent call last):
  File "cura_app.py", line 239, in <module>
  File "cura/CuraApplication.py", line 858, in run
    super().run()
  File "UM/Qt/QtApplication.py", line 381, in run
    super().run()
  File "UM/Application.py", line 274, in run
    self.startSplashWindowPhase()
  File "cura/CuraApplication.py", line 567, in startSplashWindowPhase
    self._container_registry.loadAllMetadata()
  File "cura/Settings/CuraContainerRegistry.py", line 379, in loadAllMetadata
    super().loadAllMetadata()
  File "UM/Settings/ContainerRegistry.py", line 467, in loadAllMetadata
    cursor = self._getDatabaseConnection().cursor()
  File "UM/Settings/ContainerRegistry.py", line 385, in _getDatabaseConnection
    self._db_connection = self._createDatabaseFile(db_path)
  File "UM/Settings/ContainerRegistry.py", line 363, in _createDatabaseFile
    connection = db.Connection(db_path)
sqlite3.OperationalError: unable to open database file

```

Cura log
```
Thread 0x000014f80f03e6c0 (most recent call first):
  File "UM/Backend/Backend.py", line 209 in _storeStderrToLogThread
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000014f80f23f6c0 (most recent call first):
  File "UM/Backend/Backend.py", line 189 in _storeOutputToLogThread
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000014f829bfa6c0 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM/JobQueue.py", line 98 in _nextJob
  File "UM/JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000014f829dfb6c0 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM/JobQueue.py", line 98 in _nextJob
  File "UM/JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000014f829ffc6c0 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM/JobQueue.py", line 98 in _nextJob
  File "UM/JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000014f82a1fd6c0 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM/JobQueue.py", line 98 in _nextJob
  File "UM/JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000014f82a3fe6c0 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM/JobQueue.py", line 98 in _nextJob
  File "UM/JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000014f82a5ff6c0 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM/JobQueue.py", line 98 in _nextJob
  File "UM/JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000014f82a8006c0 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM/JobQueue.py", line 98 in _nextJob
  File "UM/JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000014f82aa016c0 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM/JobQueue.py", line 98 in _nextJob
  File "UM/JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Current thread 0x000014f86d143740 (most recent call first):
  File "cura/CrashHandler.py", line 397 in _logInfoWidget
  File "cura/CrashHandler.py", line 182 in _createDialog
  File "cura/CrashHandler.py", line 86 in __init__
  File "cura_app.py", line 177 in exceptHook

```

**Comment by thelamer** [comment]
The specific file it is trying to create is `/config/.cache/cura/5.6/containers.db` 

So in your case you need to check out the path `/mnt/cache/appdata/cura/.cache/cura/5.6/containers.db` and see what could be going on with permissions. 

An easy test would be to remove the mount all together (`  -v '/mnt/cache/appdata/cura':'/config':'rw' 'lscr.io/linuxserver/cura'`)and see if it works, if so you have a permission/filesystem incompatibility.
