### ISSUE TITLE
TyepeError: Cannot read properties of undefined Error

### ISSUE THREAD

**Issue by joelstitch** [linuxserver/docker-cura#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I start the Docker container and login I get the error:

```
TyepeError: Cannot read properties of undefined (reading 'lastActiveAt')
at https://my-server-address/vnc/dist/main.bundle.js:24402:61
```

### Expected Behavior

After login I should be able to setup the serttings.

### Steps To Reproduce

1. install docker image
2. run docker container
3. login

### Environment

```markdown
- OS: Synology DSM 7.2.1-69057 Update 4
- How docker service was installed: Portainer
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "3.9"
services:
  cura:
    image: ghcr.io/linuxserver/cura:latest
    container_name: UltiMaker-Cura
    hostname: cura
    mem_limit: 4g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    ports:
      - 8232:3000
    volumes:
      - /volume1/docker/ultimakercura:/config:rw
    environment:
      TZ: US/Chicago
      PUID: 1026
      PGID: 100
      TITLE: Cura
      CUSTOM_USER: USER
      PASSWORD: PASSWORD
    restart: on-failure:5
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1026
User GID:    100
───────────────────────────────────────
..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.....+.....+............+.+...............+..+...+.+...........+...+.+...+...........+.+......+........+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..+.+.........+...+..+.......+........+......+.+..............+.........+...+....+...+..+.+..............+.+.....+.........+..........+.........+...........................+........+....+..+.........+....+..+....+.....+......+...+.......+...+...........+....+......+..+...+.+...+......+............+..+...+.........+.+..+..........+...+..............+.+..+...+....+.......................+......+.+...+...+..+...............+......+.......+..+...+...+....+......+.....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
...+..+...+.+......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.....+.....+.......+..+......+...+....+........+..................+.+........+..........+.....+...+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*....+.+...+...+............+.....+...........................+......+...+......................+..+.......+...........+.......+...+..+......+.......+.......................+.+.....+......+..................+......+......+.........+.........+.+...............+.....+...+.......+.....+.............+........+...+......+.............+.....+..........+......+......+........+.+.....+.......+...+......+......+..+...+..........+..+.......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-----
[custom-init] No custom files found, skipping...
[ls.io-init] done.
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
Xvnc KasmVNC 1.2.0 - built Feb 17 2024 18:53:30
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation
Obt-Message: Xinerama extension is not present on the server
Error: Connection refused
    at PulseAudioContext.<anonymous> (/kclient/node_modules/pulseaudio2/lib/pulse.js:120:36)
Kclient was unable to init audio, it is possible your host lacks support!!!!
PyInstaller/loader/pyimod02_importers.py:352: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
QStandardPaths: wrong permissions on runtime directory /config/.XDG, 0777 instead of 0700
(UltiMaker-Cura:291): dbind-WARNING **: 01:15:38.303: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
 2024-03-10 01:15:51,337 [INFO] websocket 0: got client connection from 127.0.0.1
 2024-03-10 01:15:51,337 [INFO] websocket 0: /websockify request failed websocket checks, not a GET request, or missing Upgrade header
 2024-03-10 01:15:51,338 [INFO] websocket 0: 127.0.0.1 181.214.165.61 - "GET /websockify HTTP/1.1" 404 180
Cyclic dependency detected between "file:///opt/cura/share/cura/resources/qml/Actions.qml" and "file:///opt/cura/share/cura/resources/qml/Actions.qml"
X connection to :1 broken (explicit kill or server shutdown).
The X11 connection broke (error 1). Did the X11 server die?
```

**Comment by thelamer** [comment]
Try without the volume for testing and drop the no new privs 

Ci looks clean https://ci-tests.linuxserver.io/linuxserver/cura/latest/index.html

**Comment by Snuffy2** [comment]
I believe I'm getting the same errors

```
cura      | [migrations] started
cura      | [migrations] no migrations found
cura      | usermod: no changes
cura      | ───────────────────────────────────────
cura      |
cura      |       ██╗     ███████╗██╗ ██████╗
cura      |       ██║     ██╔════╝██║██╔═══██╗
cura      |       ██║     ███████╗██║██║   ██║
cura      |       ██║     ╚════██║██║██║   ██║
cura      |       ███████╗███████║██║╚██████╔╝
cura      |       ╚══════╝╚══════╝╚═╝ ╚═════╝
cura      |
cura      |    Brought to you by linuxserver.io
cura      | ───────────────────────────────────────
cura      |
cura      | To support LSIO projects visit:
cura      | https://www.linuxserver.io/donate/
cura      |
cura      | ───────────────────────────────────────
cura      | GID/UID
cura      | ───────────────────────────────────────
cura      |
cura      | User UID:    911
cura      | User GID:    911
cura      | ───────────────────────────────────────
cura      |
cura      | ......+........+...+..........+..+...+.+.........+.....+......+.+...............+.....+....+.........+.....................+........+......+....+...+..+.+..+....+.....+.+..+.............+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*..............+.+........+...+....+......+..............+......+...+.+.....+...+.....................+....+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.....+.......+..+.+..+...+.......+..+.......+...+........+.......+........+....+...........+..........+.....+............+.+......+........+......+.+.....+.+..............+....+..+............+.......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
cura      | .......+.+...+..+.+............+..+.+...+............+..+.+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*...+...........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*.........+...+..........+..+.+............+......+..+.............+..+..........+.........+........+.+............+..+...+...+.+...+...........+.+....................+....+.........+.....+.+.....+.+........+.+.........+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
cura      | -----
cura      | [custom-init] No custom files found, skipping...
cura      | _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
cura      |
cura      | Xvnc KasmVNC 1.2.0 - built Mar  2 2024 18:50:50
cura      | Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
cura      | See http://kasmweb.com for information on KasmVNC.
cura      | Underlying X server release 12014000, The X.Org Foundation
cura      |
cura      | [ls.io-init] done.
cura      | Obt-Message: Xinerama extension is not present on the server
cura      | PyInstaller/loader/pyimod02_importers.py:352: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
cura      | QStandardPaths: wrong permissions on runtime directory /config/.XDG, 0755 instead of 0700
cura      |
cura      | (UltiMaker-Cura:287): dbind-WARNING **: 18:18:38.718: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
cura      | Cyclic dependency detected between "file:///opt/cura/share/cura/resources/qml/Actions.qml" and "file:///opt/cura/share/cura/resources/qml/Actions.qml"
```

```
services:
  cura:
    image: lscr.io/linuxserver/cura:latest
    hostname: cura
    container_name: cura
    logging:
      driver: json-file
    networks:
      - default
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
    ports:
      - 33000:3000
    volumes:
      #- ${APPDATA}/cura/config:/config
      - $LOCALTIME
    environment:
      TZ: $TZ
```

**Comment by j0nnymoe** [comment]
What synology models are you trying to run this on? also need kernel versions.

**Comment by homerr** [comment]
Closing this due to inactivity, also seems quite related to other issues popping up on older Synology kit with outdated kernels, which we're unable to assist with.
